config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'playlists#home'

  resources :artists do
    resources :songs
  end

  resources :songs
  resources :playlists
  get '/random', to: 'songs#random'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :artist_name, :artist_image_path, presence: true
  validates_uniqueness_of :artist_name

  has_many :songs
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  validates :name, :song_ids, presence: true
  validates_uniqueness_of :name
  
  has_many :playlistings
  has_many :songs, through: :playlistings

  def self.most_popular_song
    song_id = Song.joins(:playlists).order("count_all DESC").group(:id).count
    top_songs = song_id.select {|k,v| v == song_id.values.max}
    return_array = []

    top_songs.each do |k,v| 
      return_array << [Song.find(k), v]
    end
    return_array
  end

  def self.most_popular_artist
    final = {}
    artists = Artist.all 
    artists.each do |a|
      total_song_count = 0
      a.song_ids.each do |s|
        total_song_count += Playlisting.where(:song_id => s).count
      end
      final[a.id] = total_song_count
    end
    final.select {|k,v| v == final.values.max}
  end
end

app/models/playlisting.rb
class Playlisting < ApplicationRecord
  belongs_to :playlist
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  validates :title, presence: true
  belongs_to :artist

  has_many :playlistings
  has_many :playlists, through: :playlistings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit]

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def show
  end

  def edit
  end
  
  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else
      @errors = "Name can't be blank'"
      render :new
    end
  end

  def update
    Artist.update(params[:id], artist_params)
    redirect_to artists_path
  end

  def destroy
    Artist.delete(params[:id])
    redirect_to artists_path
  end
  
  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:artist_name, :artist_image_path)
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def home
    @playlists = Playlist.all
    @popular_songs = Playlist.most_popular_song
    @popular_artists = Playlist.most_popular_artist
  end

  def new
    @playlist = Playlist.new
    @songs = Song.all
  end

  def create
    new_playlist = Playlist.new(playlist_params)

    if new_playlist.save
      redirect_to playlist_path(new_playlist.id)
    else
      @errors = "please choose a song"
      @playlist = Playlist.new
      @songs = Song.all
      render :new
    end
  end

  def index
    @playlists = Playlist.all
  end

  def edit
    @playlist = Playlist.find(params[:id])
    @songs = Song.all
  end

  def update
    Playlist.update(params[:id], playlist_params)
    redirect_to playlist_path(params[:id])
  end

  def show
    @playlist = Playlist.find(params[:id])
    @songs = Song.find(@playlist.song_ids)
  end

  def destroy
    Playlist.delete(params[:id])
    redirect_to playlists_path
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name, :song_ids => [])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit]

  def index
    @songs = Song.all
    @popular = Song.joins(:playlists).order("count_all DESC").group(:id).count
  end

  def random
    random_number = 1 + Random.rand(Song.all.count - 1)
    @song = Song.find(random_number)
    render :show
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    new_song = @artist.songs.new(song_params)

    if new_song.save
      @song = Song.where(:title=>song_params[:title], :artist_id => params[:artist_id]).first
      redirect_to song_path(@song)
    else
      @errors = "Title cannot be blank"
      @song = @artist.songs.new 
      render :new
    end
  end

  def show
  end

  def edit
    @artist = @song.artist
  end

  def update
    Song.update(params[:id], song_params)
    redirect_to song_path()
  end

  def destroy
    if params["artist_id"]
      @song = Song.find(params[:id])
      @artist = @song.artist
      song.destroy
      redirect_to artist_path(@artist)
    else
      Song.delete(params[:id])
      redirect_to songs_path
    end
  end

  private

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/edit.html.erb
<h1>update an artist</h1>
<%= render :partial => '/layouts/artist_form' %>

app/views/artists/index.html.erb
<h1> artists </h1>
<br>
<div>
  <% @artists.each do |a| %>
    <div class="col-md-4">
      <img src="<%= a.artist_image_path%>">
      <br>
      <%= link_to a.artist_name, artist_path(a) %>
      <br>
    </div>
  <% end %>
</div>
<%= link_to 'Create an artist', new_artist_path %>

app/views/artists/main.html.erb
<h1> home page </h1>

app/views/artists/new.html.erb
<h1>create an artist</h1>
<%= render :partial => '/layouts/artist_form' %>

app/views/artists/show.html.erb
<h1><%= @artist.artist_name %></h1>
<img src="<%= @artist.artist_image_path%>">
<br>
<%= link_to "Edit", edit_artist_path(@artist) %>
<%= link_to "Delete", artist_path(@artist), :method => :delete %>
<br>
<br>
<br>
<h2> songs by this artist </h2>
<%= link_to "New song", new_artist_song_path(@artist) %>
<!-- ALPHABETIZE !!!! AND FOR FEATURE TEST -->
<div class="songs">
  <% @artist.songs.each do |s| %>
    <%= link_to s.title, song_path(s) %> - 
    <%= link_to 'Delete', song_path(s), :method => :delete %>
    <br>
  <% end %>
</div>

app/views/layouts/_artist_form.html.erb
<% if @errors %>
  <%= @errors %>
<% end %>
<%= form_for @artist do |f| %>
  <%= f.label :artist_name %>
  <%= f.text_field :artist_name %>

  <%= f.label :artist_image_path %>
  <%= f.text_field :artist_image_path %>

  <%= f.submit  %>
<% end %>

app/views/layouts/_playlist_form.html.erb
<% if @errors %>
  <%= @errors %>
<% end %>
<%= form_for(@playlist) do |f| %>
    <%= f.label 'name' %>
    <%= f.text_field :name %>

    <% @songs.each do |song| %>
      <div class="list_style">
        <div style="float:left;margin-left:5px;">
          <%= check_box_tag(:song_ids, song.id, false, :name => 'playlist[song_ids][]', id: "song-#{song.id}") %>
        </div>
        <%= song.title %>
      </div>
    <% end %>
  <%= f.submit %>
<% end %>

app/views/layouts/_song_form.html.erb
<% if @errors %>
  <%= @errors %>
<% end %>
<%= "artist = #{@artist.artist_name}" %>
<%= form_for ([@artist, @song]) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MixMaster</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Sigmar+One|Montserrat" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-text" style="color:white;" href="/">home</a>
          <a class="navbar-text" style="color:white;" href="/random">random tune</a>
        </div>
        <div class="navbar-header navbar-right">
          <a class="navbar-text" style="color:white;" href="/playlists"> playlists </a>
          <a class="navbar-text" style="color:white;" href="/artists">artists </a>
          <a class="navbar-text" style="color:white;" href="/songs"> songs </a>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/playlists/edit.html.erb
<h1> edit a playlist </h1>
<%= render :partial => '/layouts/playlist_form' %>

app/views/playlists/home.html.erb
<h1 style="width:80%; margin-left:auto; margin-right:auto;"> the top electronic sounds of all time </h1>
<p style="width:80%; margin-left:auto; margin-right:auto;">  - according to top 10 lists aggregated from premier music blogs - </p>
<br>
<div> 
  <div class="col-md-6 dash">
    <h2> best artist </h2>
    <br>
    <% @popular_artists.each do |pa| %>
      <img style="width:560px; height:315px;" src="<%= Artist.find(pa[0]).artist_image_path%>">
      <br>
      <%= link_to Artist.find(pa[0]).artist_name, artist_path(pa[0]) %>
      <br>
      <p><%= "with #{pa[1]} appearances across #{@playlists.count} playlists" %></p>
      <br>
    <% end %>
  </div>
  <div class="col-md-6 dash">
    <h2> best song </h2>
    <br>
    <% @popular_songs.each do |ps| %>
      <iframe width="560" height="315" src="<%= ps[0].youtube.gsub('watch?v=', 'embed/') %>" frameborder="0" allowfullscreen></iframe>
      <%= link_to ps[0].title, song_path(ps[0]) %>
      <br>
      <p><%= "appears on #{ps[1]} playlists" %></p>
      <br>
    <% end %>
  </div>
</div> 
<h1> playlist sources </h1>
<div>
  <% @playlists.each do |p| %>
    <div class="col-md-4">
      <%= link_to p.name, playlist_path(p) %>
      <br>
    </div>
  <% end %>
</div>
<br>
<br>
<footer class="footer">
  <div class="container">
    <p class="text-muted"> a project by nick gheorghita, using rails, postgres and bootstrap.  </p>
    <p class="text-muted"> code available <a href="https://github.com/njgheorghita/mix_master" target="_blank">here</a></p>
  </div>
</footer>

app/views/playlists/index.html.erb
<h1> all playlists </h1>
<div>
  <% @playlists.each do |p| %>
    <%= link_to p.name, playlist_path(p) %>
    <br>
  <% end %>
  <br>
  <%= link_to "create a playlist", new_playlist_path %>
</div>

app/views/playlists/new.html.erb
<h1> create a playlist </h1>
<% if @errors %>
  <%= @errors %>
<% end %>
<%= form_for(@playlist) do |f| %>
  <%= f.label 'playlist name' %>
  <%= f.text_field :name %>

  <% @songs.each do |song| %>
    <div>
      <%= check_box_tag(:song_ids, song.id, false, :name => 'playlist[song_ids][]', id: "song-#{song.id}") %>
      <%= song.title %>
    </div>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/playlists/show.html.erb
<h1><%= "#{@playlist.name}'s 10 best electronic songs" %></h1>
<% @songs.each do |s| %>
  <li><%= link_to s.title, song_path(s) %></li>
<% end %>
<br>
<%= link_to "source", @playlist.source, target: "_blank" %>
<br>
<%= link_to "Edit Playlist", edit_playlist_path(@playlist) %>
<br>
<%= link_to "Delete Playlist", playlist_path(@playlist), :method => :delete %>

app/views/songs/edit.html.erb
<h1> edit a song </h1>
<%= render :partial => '/layouts/song_form' %>

app/views/songs/index.html.erb
<h1> all songs </h1>
<table class="table songs_table">
  <thead>
    <tr>
      <th>
        title 
      </th>
      <th>
        popularity
        <br>
        (# of playlists)
      </th>
    </tr>
  </thead>
  <tbody>
    <% @songs.each do |s| %>
      <tr>
        <td>
          <%= link_to s.title, song_path(s) %> 
        </td>
        <td>
          <%= s.playlists.count %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/songs/new.html.erb
<h1> create a new song </h1>
<%= render :partial => '/layouts/song_form' %>

app/views/songs/show.html.erb
<div>
  <div class="col-md-6">
    <img src="<%= @song.artist.artist_image_path%>">
    <br>
    <h1><%= @song.title %></h1>
    <p> by </p>
    <%= link_to @song.artist.artist_name, artist_path(@song.artist) %>
    <br>
  </div>
  <div class="col-md-6">
    <iframe width="560" float="left" height="315" src="<%= @song.youtube.gsub('watch?v=', 'embed/') %>" frameborder="0" allowfullscreen></iframe>
  </div>
</div>
<br>
<h1> appears on playlists </h1>
<% @song.playlists.each do |p| %>
  <%= link_to p.name, playlist_path(p) %>
  <br>
<% end %>
<br>
<%= link_to "Edit", edit_song_path(@song) %> 
<span class="glyphicon glyphicon-minus"></span>
<%= link_to 'Delete', song_path(@song), :method => :delete %>
<br>